package ds

type Car struct {
	Name                    string
	CityDriving             bool // Указывает, подходит ли автомобиль для городской езды.
	HighwayDriving          bool // Указывает, подходит ли автомобиль для езды по шоссе.
	FuelEfficient           bool // Указывает, является ли автомобиль экономичным по расходу топлива.
	Spacious                bool // Указывает, является ли автомобиль просторным.
	Powerful                bool // Указывает, является ли автомобиль мощным.
	EasyToDrive             bool // Указывает, является ли автомобиль легким в управлении.
	Comfortable             bool // Указывает, является ли автомобиль комфортным для пассажиров.
	Sporty                  bool // Указывает, является ли автомобиль спортивным.
	ModernDesign            bool // Указывает, имеет ли автомобиль современный дизайн.
	HighEndLuxury           bool // Указывает, является ли автомобиль роскошным.
	EnvironmentallyFriendly bool // Указывает, является ли автомобиль экологически чистым.
	FWD                     bool // Передний привод
	RWD                     bool // Задний привод
	AWD                     bool // Полный привод
	RearViewCamera          bool // Камера заднего вида
	TirePressureMonitoring  bool // Контроль давления в шинах
	AutomaticParking        bool // Автоматическая парковка
	NavigationSystem        bool // Навигационная система
	HeatedSeats             bool // Подогрев сидений
	ElectricMotor           bool // Наличие электромотора
}

var Сars = []Car{
	{
		Name:                    "Toyota Corolla",
		CityDriving:             true,
		HighwayDriving:          true,
		FuelEfficient:           true,
		Spacious:                false,
		Powerful:                false,
		EasyToDrive:             true,
		Comfortable:             false,
		Sporty:                  false,
		ModernDesign:            false,
		HighEndLuxury:           false,
		EnvironmentallyFriendly: true,
		FWD:                     true,
		RWD:                     false,
		AWD:                     false,
		RearViewCamera:          true,
		TirePressureMonitoring:  true,
		AutomaticParking:        false,
		NavigationSystem:        false,
		HeatedSeats:             false,
		ElectricMotor:           false,
	},
	{
		Name:                    "Honda Civic",
		CityDriving:             true,
		HighwayDriving:          true,
		FuelEfficient:           true,
		Spacious:                false,
		Powerful:                false,
		EasyToDrive:             true,
		Comfortable:             true,
		Sporty:                  false,
		ModernDesign:            false,
		HighEndLuxury:           false,
		EnvironmentallyFriendly: true,
		FWD:                     true,
		RWD:                     false,
		AWD:                     false,
		RearViewCamera:          true,
		TirePressureMonitoring:  true,
		AutomaticParking:        false,
		NavigationSystem:        false,
		HeatedSeats:             false,
		ElectricMotor:           false,
	},
	{
		Name:                    "Mazda CX-5",
		CityDriving:             true,
		HighwayDriving:          true,
		FuelEfficient:           false,
		Spacious:                true,
		Powerful:                false,
		EasyToDrive:             false,
		Comfortable:             true,
		Sporty:                  false,
		ModernDesign:            true,
		HighEndLuxury:           false,
		EnvironmentallyFriendly: false,
		FWD:                     true,
		RWD:                     false,
		AWD:                     false,
		RearViewCamera:          true,
		TirePressureMonitoring:  true,
		AutomaticParking:        false,
		NavigationSystem:        true,
		HeatedSeats:             true,
		ElectricMotor:           false,
	},
	{
		Name:                    "Jeep Wrangler",
		CityDriving:             false,
		HighwayDriving:          false,
		FuelEfficient:           false,
		Spacious:                false,
		Powerful:                true,
		EasyToDrive:             false,
		Comfortable:             false,
		Sporty:                  true,
		ModernDesign:            false,
		HighEndLuxury:           false,
		EnvironmentallyFriendly: false,
		FWD:                     false,
		RWD:                     true,
		AWD:                     true,
		RearViewCamera:          true,
		TirePressureMonitoring:  true,
		AutomaticParking:        false,
		NavigationSystem:        false,
		HeatedSeats:             false,
		ElectricMotor:           false,
	},
	{
		Name:                    "Ford Explorer",
		CityDriving:             false,
		HighwayDriving:          true,
		FuelEfficient:           false,
		Spacious:                true,
		Powerful:                true,
		EasyToDrive:             false,
		Comfortable:             true,
		Sporty:                  false,
		ModernDesign:            false,
		HighEndLuxury:           false,
		EnvironmentallyFriendly: false,
		FWD:                     false,
		RWD:                     true,
		AWD:                     true,
		RearViewCamera:          true,
		TirePressureMonitoring:  true,
		AutomaticParking:        false,
		NavigationSystem:        true,
		HeatedSeats:             true,
		ElectricMotor:           false,
	},
	{
		Name:                    "Tesla Model S",
		CityDriving:             true,
		HighwayDriving:          true,
		FuelEfficient:           true,
		Spacious:                true,
		Powerful:                true,
		EasyToDrive:             true,
		Comfortable:             true,
		Sporty:                  false,
		ModernDesign:            true,
		HighEndLuxury:           true,
		EnvironmentallyFriendly: true,
		FWD:                     true,
		RWD:                     false,
		AWD:                     false,
		RearViewCamera:          true,
		TirePressureMonitoring:  true,
		AutomaticParking:        true,
		NavigationSystem:        true,
		HeatedSeats:             true,
		ElectricMotor:           true,
	},
	{
		Name:                    "BMW 3 Series",
		CityDriving:             true,
		HighwayDriving:          true,
		FuelEfficient:           false,
		Spacious:                false,
		Powerful:                true,
		EasyToDrive:             false,
		Comfortable:             true,
		Sporty:                  true,
		ModernDesign:            false,
		HighEndLuxury:           false,
		EnvironmentallyFriendly: false,
		FWD:                     false,
		RWD:                     true,
		AWD:                     false,
		RearViewCamera:          true,
		TirePressureMonitoring:  true,
		AutomaticParking:        false,
		NavigationSystem:        true,
		HeatedSeats:             true,
		ElectricMotor:           false,
	},
	{
		Name:                    "Audi A4",
		CityDriving:             true,
		HighwayDriving:          true,
		FuelEfficient:           false,
		Spacious:                false,
		Powerful:                true,
		EasyToDrive:             false,
		Comfortable:             true,
		Sporty:                  false,
		ModernDesign:            true,
		HighEndLuxury:           false,
		EnvironmentallyFriendly: false,
		FWD:                     true,
		RWD:                     false,
		AWD:                     false,
		RearViewCamera:          true,
		TirePressureMonitoring:  true,
		AutomaticParking:        false,
		NavigationSystem:        true,
		HeatedSeats:             true,
		ElectricMotor:           false,
	},
	{
		Name:                    "Mercedes-Benz C-Class",
		CityDriving:             true,
		HighwayDriving:          true,
		FuelEfficient:           false,
		Spacious:                false,
		Powerful:                true,
		EasyToDrive:             false,
		Comfortable:             true,
		Sporty:                  false,
		ModernDesign:            false,
		HighEndLuxury:           true,
		EnvironmentallyFriendly: false,
		FWD:                     true,
		RWD:                     false,
		AWD:                     false,
		RearViewCamera:          true,
		TirePressureMonitoring:  true,
		AutomaticParking:        false,
		NavigationSystem:        true,
		HeatedSeats:             true,
		ElectricMotor:           false,
	},
	{
		Name:                    "Porsche 911",
		CityDriving:             false,
		HighwayDriving:          false,
		FuelEfficient:           false,
		Spacious:                false,
		Powerful:                true,
		EasyToDrive:             false,
		Comfortable:             false,
		Sporty:                  true,
		ModernDesign:            false,
		HighEndLuxury:           true,
		EnvironmentallyFriendly: false,
		FWD:                     false,
		RWD:                     true,
		AWD:                     false,
		RearViewCamera:          true,
		TirePressureMonitoring:  true,
		AutomaticParking:        false,
		NavigationSystem:        false,
		HeatedSeats:             false,
		ElectricMotor:           false,
	},
}
